#!/bin/bash

apt-get update
apt-get upgrade
apt update --fix-missing
apt-get install -y adduser
apt-get install -y adwaita-icon-theme
apt-get install -y alsa-topology-conf
apt-get install -y alsa-ucm-conf
apt-get install -y apache2-bin
apt-get install -y apache2-data
apt-get install -y apache2-utils
apt-get install -y apache2
apt-get install -y apparmor
apt-get install -y apt-transport-https
apt-get install -y apt
apt-get install -y aspell-en
apt-get install -y aspell
apt-get install -y at-spi2-core
apt-get install -y autoconf
apt-get install -y automake
apt-get install -y autotools-dev
apt-get install -y avahi-daemon
apt-get install -y base-files
apt-get install -y base-passwd
apt-get install -y bash
apt-get install -y bind9-host
apt-get install -y bind9-libs
apt-get install -y binfmt-support
apt-get install -y binutils-common
apt-get install -y binutils-x86-64-linux-gnu
apt-get install -y binutils
apt-get install -y blt
apt-get install -y brz
apt-get install -y bsdextrautils
apt-get install -y bsdutils
apt-get install -y bubblewrap
apt-get install -y build-essential
apt-get install -y bzip2-doc
apt-get install -y bzip2
apt-get install -y bzr
apt-get install -y ca-certificates-java
apt-get install -y ca-certificates
apt-get install -y catch2
apt-get install -y clang-14
apt-get install -y clang-format-14
apt-get install -y clang-format
apt-get install -y cmake-data
apt-get install -y cmake
apt-get install -y comerr-dev
apt-get install -y coreutils
apt-get install -y cpp-11
apt-get install -y cpp
apt-get install -y cppcheck
apt-get install -y curl
apt-get install -y cvs
apt-get install -y cvsps
apt-get install -y cython3
apt-get install -y dash
apt-get install -y dbus-user-session
apt-get install -y dbus
apt-get install -y dconf-gsettings-backend
apt-get install -y dconf-service
apt-get install -y debconf
apt-get install -y debianutils
apt-get install -y default-jdk-headless
apt-get install -y default-jdk
apt-get install -y default-jre-headless
apt-get install -y default-jre
apt-get install -y default-libmysqlclient-dev
apt-get install -y desktop-file-utils
apt-get install -y dh-elpa-helper
apt-get install -y dictionaries-common
apt-get install -y diffutils
apt-get install -y dirmngr
apt-get install -y distro-info-data
apt-get install -y dmidecode
apt-get install -y dmsetup
apt-get install -y docbook-xml
apt-get install -y docutils-common
apt-get install -y dosfstools
apt-get install -y dpkg-dev
apt-get install -y dpkg
apt-get install -y e2fsprogs
apt-get install -y eject
apt-get install -y emacsen-common
apt-get install -y enchant-2
apt-get install -y evince-common
apt-get install -y evince
apt-get install -y fakeroot
apt-get install -y fdisk
apt-get install -y feh
apt-get install -y file
apt-get install -y findutils
apt-get install -y firefox
apt-get install -y fontconfig-config
apt-get install -y fontconfig
apt-get install -y fonts-dejavu-core
apt-get install -y fonts-dejavu-extra
apt-get install -y fonts-droid-fallback
apt-get install -y fonts-liberation
apt-get install -y fonts-lyx
apt-get install -y fonts-noto-mono
apt-get install -y fonts-urw-base35
apt-get install -y freeglut3-dev
apt-get install -y freeglut3
apt-get install -y fuse3
apt-get install -y g++-11
apt-get install -y g++
apt-get install -y gazebo-common
apt-get install -y gazebo-plugin-base
apt-get install -y gazebo
apt-get install -y gcc-11-base
apt-get install -y gcc-11
apt-get install -y gcc-12-base
apt-get install -y gcc
apt-get install -y gcr
apt-get install -y gdal-data
apt-get install -y gdb
apt-get install -y gdbserver
apt-get install -y gdisk
apt-get install -y gedit-common
apt-get install -y gedit
apt-get install -y geoclue-2.0
apt-get install -y gfortran-11
apt-get install -y gfortran
apt-get install -y ghostscript
apt-get install -y gir1.2-atk-1.0
apt-get install -y gir1.2-freedesktop
apt-get install -y gir1.2-gdkpixbuf-2.0
apt-get install -y gir1.2-glib-2.0
apt-get install -y gir1.2-gtk-3.0
apt-get install -y gir1.2-gtksource-4
apt-get install -y gir1.2-harfbuzz-0.0
apt-get install -y gir1.2-ibus-1.0
apt-get install -y gir1.2-packagekitglib-1.0
apt-get install -y gir1.2-pango-1.0
apt-get install -y gir1.2-peas-1.0
apt-get install -y git-all
apt-get install -y git-cvs
apt-get install -y git-doc
apt-get install -y git-email
apt-get install -y git-gui
apt-get install -y git-man
apt-get install -y git-mediawiki
apt-get install -y git-svn
apt-get install -y git
apt-get install -y gitk
apt-get install -y gitweb
apt-get install -y glib-networking-common
apt-get install -y glib-networking-services
apt-get install -y glib-networking
apt-get install -y gnome-desktop3-data
apt-get install -y gnome-keyring-pkcs11
apt-get install -y gnome-keyring
apt-get install -y gnupg-l10n
apt-get install -y gnupg-utils
apt-get install -y gnupg
apt-get install -y google-mock
apt-get install -y googletest
apt-get install -y gpg-agent
apt-get install -y gpg-wks-client
apt-get install -y gpg-wks-server
apt-get install -y gpg
apt-get install -y gpgconf
apt-get install -y gpgsm
apt-get install -y gpgv
apt-get install -y graphicsmagick-libmagick-dev-compat
apt-get install -y graphviz
apt-get install -y grep
apt-get install -y groff-base
apt-get install -y gsettings-desktop-schemas
apt-get install -y gsfonts
apt-get install -y gstreamer1.0-gl
apt-get install -y gstreamer1.0-plugins-base
apt-get install -y gstreamer1.0-plugins-good
apt-get install -y gstreamer1.0-x
apt-get install -y gtk-update-icon-cache
apt-get install -y gvfs-backends
apt-get install -y gvfs-common
apt-get install -y gvfs-daemons
apt-get install -y gvfs-libs
apt-get install -y gvfs
apt-get install -y gzip
apt-get install -y hdf5-helpers
apt-get install -y hicolor-icon-theme
apt-get install -y hostname
apt-get install -y humanity-icon-theme
apt-get install -y hunspell-en-us
apt-get install -y i965-va-driver
apt-get install -y ibverbs-providers
apt-get install -y icu-devtools
apt-get install -y iio-sensor-proxy
apt-get install -y init-system-helpers
apt-get install -y intel-media-va-driver
apt-get install -y iso-codes
apt-get install -y java-common
apt-get install -y javascript-common
apt-get install -y krb5-multidev
apt-get install -y lcov
apt-get install -y less
apt-get install -y lib32gcc-s1
apt-get install -y lib32stdc++6
apt-get install -y libaa1
apt-get install -y libaacs0
apt-get install -y libabsl-dev
apt-get install -y libabsl20210324
apt-get install -y libacl1
apt-get install -y libaec-dev
apt-get install -y libaec0
apt-get install -y libalgorithm-c3-perl
apt-get install -y libalgorithm-diff-perl
apt-get install -y libalgorithm-diff-xs-perl
apt-get install -y libalgorithm-merge-perl
apt-get install -y libamd2
apt-get install -y libann0
apt-get install -y libaom-dev
apt-get install -y libaom3
apt-get install -y libapparmor1
apt-get install -y libappstream4
apt-get install -y libapr1
apt-get install -y libaprutil1-dbd-sqlite3
apt-get install -y libaprutil1-ldap
apt-get install -y libaprutil1
apt-get install -y libapt-pkg6.0
apt-get install -y libarchive13
apt-get install -y libargon2-1
apt-get install -y libarmadillo-dev
apt-get install -y libarmadillo10
apt-get install -y libarpack2-dev
apt-get install -y libarpack2
apt-get install -y libasan6
apt-get install -y libasio-dev
apt-get install -y libasound2-data
apt-get install -y libasound2-dev
apt-get install -y libasound2
apt-get install -y libaspell15
apt-get install -y libass9
apt-get install -y libassimp-dev
apt-get install -y libassimp5
apt-get install -y libassuan0
apt-get install -y libasyncns0
apt-get install -y libatasmart4
apt-get install -y libatk-bridge2.0-0
apt-get install -y libatk-wrapper-java-jni
apt-get install -y libatk-wrapper-java
apt-get install -y libatk1.0-0
apt-get install -y libatk1.0-data
apt-get install -y libatomic1
apt-get install -y libatspi2.0-0
apt-get install -y libattr1
apt-get install -y libaudit-common
apt-get install -y libaudit1
apt-get install -y libauthen-sasl-perl
apt-get install -y libavahi-client3
apt-get install -y libavahi-common-data
apt-get install -y libavahi-common3
apt-get install -y libavahi-core7
apt-get install -y libavahi-glib1
apt-get install -y libavc1394-0
apt-get install -y libavcodec-dev
apt-get install -y libavcodec58
apt-get install -y libavdevice-dev
apt-get install -y libavdevice58
apt-get install -y libavfilter-dev
apt-get install -y libavfilter7
apt-get install -y libavformat-dev
apt-get install -y libavformat58
apt-get install -y libavutil-dev
apt-get install -y libavutil56
apt-get install -y libb-hooks-endofscope-perl
apt-get install -y libb-hooks-op-check-perl
apt-get install -y libbabeltrace1
apt-get install -y libbdplus0
apt-get install -y libbenchmark-dev
apt-get install -y libbenchmark1
apt-get install -y libbinutils
apt-get install -y libblas3
apt-get install -y libblkid-dev
apt-get install -y libblkid1
apt-get install -y libblockdev-crypto2
apt-get install -y libblockdev-fs2
apt-get install -y libblockdev-loop2
apt-get install -y libblockdev-part-err2
apt-get install -y libblockdev-part2
apt-get install -y libblockdev-swap2
apt-get install -y libblockdev-utils2
apt-get install -y libblockdev2
apt-get install -y libblosc-dev
apt-get install -y libblosc1
apt-get install -y libbluray2
apt-get install -y libboost-all-dev
apt-get install -y libboost-atomic-dev
apt-get install -y libboost-atomic1.74-dev
apt-get install -y libboost-atomic1.74.0
apt-get install -y libboost-chrono-dev
apt-get install -y libboost-chrono1.74-dev
apt-get install -y libboost-chrono1.74.0
apt-get install -y libboost-container-dev
apt-get install -y libboost-container1.74-dev
apt-get install -y libboost-container1.74.0
apt-get install -y libboost-context-dev
apt-get install -y libboost-context1.74-dev
apt-get install -y libboost-context1.74.0
apt-get install -y libboost-coroutine-dev
apt-get install -y libboost-coroutine1.74-dev
apt-get install -y libboost-coroutine1.74.0
apt-get install -y libboost-date-time-dev
apt-get install -y libboost-date-time1.74-dev
apt-get install -y libboost-date-time1.74.0
apt-get install -y libboost-dev
apt-get install -y libboost-exception-dev
apt-get install -y libboost-exception1.74-dev
apt-get install -y libboost-fiber-dev
apt-get install -y libboost-fiber1.74-dev
apt-get install -y libboost-fiber1.74.0
apt-get install -y libboost-filesystem-dev
apt-get install -y libboost-filesystem1.74-dev
apt-get install -y libboost-filesystem1.74.0
apt-get install -y libboost-graph-dev
apt-get install -y libboost-graph-parallel-dev
apt-get install -y libboost-graph-parallel1.74-dev
apt-get install -y libboost-graph-parallel1.74.0
apt-get install -y libboost-graph1.74-dev
apt-get install -y libboost-graph1.74.0
apt-get install -y libboost-iostreams-dev
apt-get install -y libboost-iostreams1.74-dev
apt-get install -y libboost-iostreams1.74.0
apt-get install -y libboost-locale-dev
apt-get install -y libboost-locale1.74-dev
apt-get install -y libboost-locale1.74.0
apt-get install -y libboost-log-dev
apt-get install -y libboost-log1.74-dev
apt-get install -y libboost-log1.74.0
apt-get install -y libboost-math-dev
apt-get install -y libboost-math1.74-dev
apt-get install -y libboost-math1.74.0
apt-get install -y libboost-mpi-dev
apt-get install -y libboost-mpi-python-dev
apt-get install -y libboost-mpi-python1.74-dev
apt-get install -y libboost-mpi-python1.74.0
apt-get install -y libboost-mpi1.74-dev
apt-get install -y libboost-mpi1.74.0
apt-get install -y libboost-nowide-dev
apt-get install -y libboost-nowide1.74-dev
apt-get install -y libboost-nowide1.74.0
apt-get install -y libboost-numpy-dev
apt-get install -y libboost-numpy1.74-dev
apt-get install -y libboost-numpy1.74.0
apt-get install -y libboost-program-options-dev
apt-get install -y libboost-program-options1.74-dev
apt-get install -y libboost-program-options1.74.0
apt-get install -y libboost-python-dev
apt-get install -y libboost-python1.74-dev
apt-get install -y libboost-python1.74.0
apt-get install -y libboost-random-dev
apt-get install -y libboost-random1.74-dev
apt-get install -y libboost-random1.74.0
apt-get install -y libboost-regex-dev
apt-get install -y libboost-regex1.74-dev
apt-get install -y libboost-regex1.74.0
apt-get install -y libboost-serialization-dev
apt-get install -y libboost-serialization1.74-dev
apt-get install -y libboost-serialization1.74.0
apt-get install -y libboost-stacktrace-dev
apt-get install -y libboost-stacktrace1.74-dev
apt-get install -y libboost-stacktrace1.74.0
apt-get install -y libboost-system-dev
apt-get install -y libboost-system1.74-dev
apt-get install -y libboost-system1.74.0
apt-get install -y libboost-test-dev
apt-get install -y libboost-test1.74-dev
apt-get install -y libboost-test1.74.0
apt-get install -y libboost-thread-dev
apt-get install -y libboost-thread1.74-dev
apt-get install -y libboost-thread1.74.0
apt-get install -y libboost-timer-dev
apt-get install -y libboost-timer1.74-dev
apt-get install -y libboost-timer1.74.0
apt-get install -y libboost-tools-dev
apt-get install -y libboost-type-erasure-dev
apt-get install -y libboost-type-erasure1.74-dev
apt-get install -y libboost-type-erasure1.74.0
apt-get install -y libboost-wave-dev
apt-get install -y libboost-wave1.74-dev
apt-get install -y libboost-wave1.74.0
apt-get install -y libboost1.74-dev
apt-get install -y libboost1.74-tools-dev
apt-get install -y libbrotli-dev
apt-get install -y libbrotli1
apt-get install -y libbs2b0
apt-get install -y libbsd-dev
apt-get install -y libbsd0
apt-get install -y libbtf1
apt-get install -y libbullet-dev
apt-get install -y libbullet3.06
apt-get install -y libbz2-1.0
apt-get install -y libbz2-dev
apt-get install -y libc-bin
apt-get install -y libc-dev-bin
apt-get install -y libc-devtools
apt-get install -y libc6-dbg
apt-get install -y libc6-dev
apt-get install -y libc6-i386
apt-get install -y libc6
apt-get install -y libcaca0
apt-get install -y libcaf-openmpi-3
apt-get install -y libcairo-gobject2
apt-get install -y libcairo-script-interpreter2
apt-get install -y libcairo2-dev
apt-get install -y libcairo2
apt-get install -y libcamd2
apt-get install -y libcanberra0
apt-get install -y libcap-ng0
apt-get install -y libcap2-bin
apt-get install -y libcap2
apt-get install -y libcbor0.8
apt-get install -y libcc1-0
apt-get install -y libccd-dev
apt-get install -y libccd2
apt-get install -y libccolamd2
apt-get install -y libcdio-cdda2
apt-get install -y libcdio-paranoia2
apt-get install -y libcdio19
apt-get install -y libcdparanoia0
apt-get install -y libcdt5
apt-get install -y libceres-dev
apt-get install -y libceres2
apt-get install -y libcfitsio-dev
apt-get install -y libcfitsio-doc
apt-get install -y libcfitsio9
apt-get install -y libcgi-fast-perl
apt-get install -y libcgi-pm-perl
apt-get install -y libcgraph6
apt-get install -y libcharls-dev
apt-get install -y libcharls2
apt-get install -y libcholmod3
apt-get install -y libchromaprint1
apt-get install -y libclang-common-14-dev
apt-get install -y libclang-cpp14
apt-get install -y libclang1-14
apt-get install -y libclass-c3-perl
apt-get install -y libclass-c3-xs-perl
apt-get install -y libclass-data-inheritable-perl
apt-get install -y libclass-inspector-perl
apt-get install -y libclass-method-modifiers-perl
apt-get install -y libclass-singleton-perl
apt-get install -y libclass-xsaccessor-perl
apt-get install -y libclone-perl
apt-get install -y libcoarrays-dev
apt-get install -y libcoarrays-openmpi-dev
apt-get install -y libcodec2-1.0
apt-get install -y libcolamd2
apt-get install -y libcolord2
apt-get install -y libcom-err2
apt-get install -y libcommon-sense-perl
apt-get install -y libconsole-bridge-dev
apt-get install -y libconsole-bridge1.0
apt-get install -y libcrypt-dev
apt-get install -y libcrypt1
apt-get install -y libcryptsetup12
apt-get install -y libctf-nobfd0
apt-get install -y libctf0
apt-get install -y libcue2
apt-get install -y libcups2
apt-get install -y libcurl3-gnutls
apt-get install -y libcurl4-openssl-dev
apt-get install -y libcurl4
apt-get install -y libcxsparse3
apt-get install -y libdaemon0
apt-get install -y libdart-collision-bullet6.12
apt-get install -y libdart-dev
apt-get install -y libdart-external-convhull-3d-dev
apt-get install -y libdart-external-odelcpsolver-dev
apt-get install -y libdart-external-odelcpsolver6.12
apt-get install -y libdart-utils6.12
apt-get install -y libdart6.12
apt-get install -y libdata-dump-perl
apt-get install -y libdata-optlist-perl
apt-get install -y libdatetime-format-builder-perl
apt-get install -y libdatetime-format-iso8601-perl
apt-get install -y libdatetime-format-strptime-perl
apt-get install -y libdatetime-locale-perl
apt-get install -y libdatetime-perl
apt-get install -y libdatetime-timezone-perl
apt-get install -y libdatrie1
apt-get install -y libdav1d-dev
apt-get install -y libdav1d5
apt-get install -y libdb5.3
apt-get install -y libdbd-sqlite3-perl
apt-get install -y libdbi-perl
apt-get install -y libdbus-1-3
apt-get install -y libdbus-1-dev
apt-get install -y libdbusmenu-glib4
apt-get install -y libdc1394-25
apt-get install -y libdc1394-dev
apt-get install -y libdconf1
apt-get install -y libde265-0
apt-get install -y libde265-dev
apt-get install -y libdebconfclient0
apt-get install -y libdebuginfod-common
apt-get install -y libdebuginfod1
apt-get install -y libdecor-0-0
apt-get install -y libdecor-0-dev
apt-get install -y libdecor-0-plugin-1-cairo
apt-get install -y libdee-1.0-4
apt-get install -y libdeflate-dev
apt-get install -y libdeflate0
apt-get install -y libdevel-callchecker-perl
apt-get install -y libdevel-caller-perl
apt-get install -y libdevel-lexalias-perl
apt-get install -y libdevel-stacktrace-perl
apt-get install -y libdevmapper1.02.1
apt-get install -y libdigest-bubblebabble-perl
apt-get install -y libdigest-hmac-perl
apt-get install -y libdjvulibre-text
apt-get install -y libdjvulibre21
apt-get install -y libdouble-conversion-dev
apt-get install -y libdouble-conversion3
apt-get install -y libdpkg-perl
apt-get install -y libdraco-dev
apt-get install -y libdraco4
apt-get install -y libdrm-amdgpu1
apt-get install -y libdrm-common
apt-get install -y libdrm-dev
apt-get install -y libdrm-intel1
apt-get install -y libdrm-nouveau2
apt-get install -y libdrm-radeon1
apt-get install -y libdrm2
apt-get install -y libdv4
apt-get install -y libdw-dev
apt-get install -y libdw1
apt-get install -y libdynaloader-functions-perl
apt-get install -y libedit2
apt-get install -y libegl-dev
apt-get install -y libegl-mesa0
apt-get install -y libegl1-mesa-dev
apt-get install -y libegl1
apt-get install -y libeigen3-dev
apt-get install -y libelf-dev
apt-get install -y libelf1
apt-get install -y libemail-valid-perl
apt-get install -y libenchant-2-2
apt-get install -y libencode-locale-perl
apt-get install -y libepoxy0
apt-get install -y liberror-perl
apt-get install -y libeval-closure-perl
apt-get install -y libevdev2
apt-get install -y libevdocument3-4
apt-get install -y libevent-2.1-7
apt-get install -y libevent-core-2.1-7
apt-get install -y libevent-dev
apt-get install -y libevent-extra-2.1-7
apt-get install -y libevent-openssl-2.1-7
apt-get install -y libevent-pthreads-2.1-7
apt-get install -y libevview3-3
apt-get install -y libexception-class-perl
apt-get install -y libexempi8
apt-get install -y libexif-dev
apt-get install -y libexif-doc
apt-get install -y libexif12
apt-get install -y libexiv2-27
apt-get install -y libexpat1-dev
apt-get install -y libexpat1
apt-get install -y libext2fs2
apt-get install -y libfabric1
apt-get install -y libfakeroot
apt-get install -y libfcgi-bin
apt-get install -y libfcgi-perl
apt-get install -y libfcgi0ldbl
apt-get install -y libfcl-dev
apt-get install -y libfcl0.7
apt-get install -y libfdisk1
apt-get install -y libffi-dev
apt-get install -y libffi8
apt-get install -y libfido2-1
apt-get install -y libfile-basedir-perl
apt-get install -y libfile-desktopentry-perl
apt-get install -y libfile-fcntllock-perl
apt-get install -y libfile-listing-perl
apt-get install -y libfile-mimeinfo-perl
apt-get install -y libfile-sharedir-perl
apt-get install -y libflac8
apt-get install -y libflann-dev
apt-get install -y libflann1.9
apt-get install -y libflite1
apt-get install -y libfmt-dev
apt-get install -y libfmt8
apt-get install -y libfont-afm-perl
apt-get install -y libfontconfig-dev
apt-get install -y libfontconfig1-dev
apt-get install -y libfontconfig1
apt-get install -y libfontenc1
apt-get install -y libfreeimage-dev
apt-get install -y libfreeimage3
apt-get install -y libfreenect-dev
apt-get install -y libfreenect0.5
apt-get install -y libfreetype-dev
apt-get install -y libfreetype6-dev
apt-get install -y libfreetype6
apt-get install -y libfreexl-dev
apt-get install -y libfreexl1
apt-get install -y libfribidi0
apt-get install -y libfuse3-3
apt-get install -y libfyba-dev
apt-get install -y libfyba0
apt-get install -y libgazebo-dev
apt-get install -y libgazebo11
apt-get install -y libgbm-dev
apt-get install -y libgbm1
apt-get install -y libgc1
apt-get install -y libgcc-11-dev
apt-get install -y libgcc-s1
apt-get install -y libgck-1-0
apt-get install -y libgcr-base-3-1
apt-get install -y libgcr-ui-3-1
apt-get install -y libgcrypt20
apt-get install -y libgd-perl
apt-get install -y libgd3
apt-get install -y libgdal-dev
apt-get install -y libgdal30
apt-get install -y libgdata-common
apt-get install -y libgdata22
apt-get install -y libgdbm-compat4
apt-get install -y libgdbm6
apt-get install -y libgdcm-dev
apt-get install -y libgdcm3.0
apt-get install -y libgdk-pixbuf-2.0-0
apt-get install -y libgdk-pixbuf2.0-bin
apt-get install -y libgdk-pixbuf2.0-common
apt-get install -y libgeographic-dev
apt-get install -y libgeographic19
apt-get install -y libgeos-c1v5
apt-get install -y libgeos-dev
apt-get install -y libgeos3.10.2
apt-get install -y libgeotiff-dev
apt-get install -y libgeotiff5
apt-get install -y libgexiv2-2
apt-get install -y libgflags-dev
apt-get install -y libgflags2.2
apt-get install -y libgfortran-11-dev
apt-get install -y libgfortran5
apt-get install -y libgif-dev
apt-get install -y libgif7
apt-get install -y libgirepository-1.0-1
apt-get install -y libgl-dev
apt-get install -y libgl1-amber-dri
apt-get install -y libgl1-mesa-dev
apt-get install -y libgl1-mesa-dri
apt-get install -y libgl1
apt-get install -y libgl2ps-dev
apt-get install -y libgl2ps1.4
apt-get install -y libglapi-mesa
apt-get install -y libgles-dev
apt-get install -y libgles1
apt-get install -y libgles2
apt-get install -y libglew-dev
apt-get install -y libglew2.2
apt-get install -y libglib2.0-0
apt-get install -y libglib2.0-bin
apt-get install -y libglib2.0-data
apt-get install -y libglib2.0-dev-bin
apt-get install -y libglib2.0-dev
apt-get install -y libglu1-mesa-dev
apt-get install -y libglu1-mesa
apt-get install -y libglvnd-core-dev
apt-get install -y libglvnd-dev
apt-get install -y libglvnd0
apt-get install -y libglx-dev
apt-get install -y libglx-mesa0
apt-get install -y libglx0
apt-get install -y libgme0
apt-get install -y libgmp10
apt-get install -y libgnome-autoar-0-0
apt-get install -y libgnome-desktop-3-19
apt-get install -y libgnutls30
apt-get install -y libgoa-1.0-0b
apt-get install -y libgoa-1.0-common
apt-get install -y libgomp1
apt-get install -y libgoogle-glog-dev
apt-get install -y libgoogle-glog0v5
apt-get install -y libgpg-error0
apt-get install -y libgpgme11
apt-get install -y libgphoto2-6
apt-get install -y libgphoto2-dev
apt-get install -y libgphoto2-l10n
apt-get install -y libgphoto2-port12
apt-get install -y libgpm2
apt-get install -y libgraphblas-dev
apt-get install -y libgraphblas6
apt-get install -y libgraphene-1.0-0
apt-get install -y libgraphics-magick-perl
apt-get install -y libgraphicsmagick++-q16-12
apt-get install -y libgraphicsmagick++1-dev
apt-get install -y libgraphicsmagick-q16-3
apt-get install -y libgraphicsmagick1-dev
apt-get install -y libgraphite2-3
apt-get install -y libgs9-common
apt-get install -y libgs9
apt-get install -y libgsf-1-114
apt-get install -y libgsf-1-common
apt-get install -y libgsm1
apt-get install -y libgspell-1-2
apt-get install -y libgspell-1-common
apt-get install -y libgssapi-krb5-2
apt-get install -y libgssrpc4
apt-get install -y libgstreamer-gl1.0-0
apt-get install -y libgstreamer-plugins-base1.0-0
apt-get install -y libgstreamer-plugins-good1.0-0
apt-get install -y libgstreamer1.0-0
apt-get install -y libgtest-dev
apt-get install -y libgtk-3-0
apt-get install -y libgtk-3-bin
apt-get install -y libgtk-3-common
apt-get install -y libgtksourceview-4-0
apt-get install -y libgtksourceview-4-common
apt-get install -y libgts-0.7-5
apt-get install -y libgts-bin
apt-get install -y libgts-dev
apt-get install -y libgudev-1.0-0
apt-get install -y libgvc6
apt-get install -y libgvpr2
apt-get install -y libgxps2
apt-get install -y libhandy-1-0
apt-get install -y libharfbuzz-icu0
apt-get install -y libharfbuzz0b
apt-get install -y libhdf4-0-alt
apt-get install -y libhdf4-alt-dev
apt-get install -y libhdf5-103-1
apt-get install -y libhdf5-cpp-103-1
apt-get install -y libhdf5-dev
apt-get install -y libhdf5-fortran-102
apt-get install -y libhdf5-hl-100
apt-get install -y libhdf5-hl-cpp-100
apt-get install -y libhdf5-hl-fortran-100
apt-get install -y libhdf5-mpi-dev
apt-get install -y libhdf5-openmpi-103-1
apt-get install -y libhdf5-openmpi-cpp-103-1
apt-get install -y libhdf5-openmpi-dev
apt-get install -y libhdf5-openmpi-fortran-102
apt-get install -y libhdf5-openmpi-hl-100
apt-get install -y libhdf5-openmpi-hl-cpp-100
apt-get install -y libhdf5-openmpi-hl-fortran-100
apt-get install -y libheif-dev
apt-get install -y libheif1
apt-get install -y libhogweed6
apt-get install -y libhtml-form-perl
apt-get install -y libhtml-format-perl
apt-get install -y libhtml-parser-perl
apt-get install -y libhtml-tagset-perl
apt-get install -y libhtml-tree-perl
apt-get install -y libhttp-cookies-perl
apt-get install -y libhttp-daemon-perl
apt-get install -y libhttp-date-perl
apt-get install -y libhttp-message-perl
apt-get install -y libhttp-negotiate-perl
apt-get install -y libhunspell-1.7-0
apt-get install -y libhwloc-dev
apt-get install -y libhwloc-plugins
apt-get install -y libhwloc15
apt-get install -y libhyphen0
apt-get install -y libibus-1.0-5
apt-get install -y libibus-1.0-dev
apt-get install -y libibverbs-dev
apt-get install -y libibverbs1
apt-get install -y libice-dev
apt-get install -y libice6
apt-get install -y libicu-dev
apt-get install -y libicu70
apt-get install -y libid3tag0
apt-get install -y libidn12
apt-get install -y libidn2-0
apt-get install -y libiec61883-0
apt-get install -y libigdgmm12
apt-get install -y libignition-cmake2-dev
apt-get install -y libignition-common3-3
apt-get install -y libignition-common3-av-dev
apt-get install -y libignition-common3-av3
apt-get install -y libignition-common3-core-dev
apt-get install -y libignition-common3-dev
apt-get install -y libignition-common3-events3
apt-get install -y libignition-common3-graphics-dev
apt-get install -y libignition-common3-graphics3
apt-get install -y libignition-common3-profiler3
apt-get install -y libignition-fuel-tools4-4
apt-get install -y libignition-fuel-tools4-dev
apt-get install -y libignition-math6-dev
apt-get install -y libignition-math6
apt-get install -y libignition-msgs5-5
apt-get install -y libignition-msgs5-dev
apt-get install -y libignition-transport8-8
apt-get install -y libignition-transport8-dev
apt-get install -y libijs-0.35
apt-get install -y libilmbase-dev
apt-get install -y libilmbase25
apt-get install -y libimagequant0
apt-get install -y libimlib2
apt-get install -y libimobiledevice6
apt-get install -y libinput-bin
apt-get install -y libinput10
apt-get install -y libio-html-perl
apt-get install -y libio-socket-ssl-perl
apt-get install -y libio-stringy-perl
apt-get install -y libip4tc2
apt-get install -y libipc-system-simple-perl
apt-get install -y libipt2
apt-get install -y libisl23
apt-get install -y libitm1
apt-get install -y libjack-jackd2-0
apt-get install -y libjansson4
apt-get install -y libjavascriptcoregtk-4.0-18
apt-get install -y libjbig-dev
apt-get install -y libjbig0
apt-get install -y libjbig2dec0
apt-get install -y libjpeg-dev
apt-get install -y libjpeg-progs
apt-get install -y libjpeg-turbo8-dev
apt-get install -y libjpeg-turbo8
apt-get install -y libjpeg8-dev
apt-get install -y libjpeg8
apt-get install -y libjpeg9
apt-get install -y libjs-jquery-hotkeys
apt-get install -y libjs-jquery-isonscreen
apt-get install -y libjs-jquery-metadata
apt-get install -y libjs-jquery-tablesorter
apt-get install -y libjs-jquery-throttle-debounce
apt-get install -y libjs-jquery-ui
apt-get install -y libjs-jquery
apt-get install -y libjs-sphinxdoc
apt-get install -y libjs-underscore
apt-get install -y libjson-c-dev
apt-get install -y libjson-c5
apt-get install -y libjson-glib-1.0-0
apt-get install -y libjson-glib-1.0-common
apt-get install -y libjson-perl
apt-get install -y libjson-xs-perl
apt-get install -y libjsoncpp-dev
apt-get install -y libjsoncpp25
apt-get install -y libjxr0
apt-get install -y libk5crypto3
apt-get install -y libkadm5clnt-mit12
apt-get install -y libkadm5srv-mit12
apt-get install -y libkdb5-10
apt-get install -y libkeyutils1
apt-get install -y libklu1
apt-get install -y libkml-dev
apt-get install -y libkmlbase1
apt-get install -y libkmlconvenience1
apt-get install -y libkmldom1
apt-get install -y libkmlengine1
apt-get install -y libkmlregionator1
apt-get install -y libkmlxsd1
apt-get install -y libkmod2
apt-get install -y libkpathsea6
apt-get install -y libkrb5-3
apt-get install -y libkrb5-dev
apt-get install -y libkrb5support0
apt-get install -y libksba8
apt-get install -y liblab-gamut1
apt-get install -y liblapack-dev
apt-get install -y liblapack3
apt-get install -y liblbfgsb0
apt-get install -y liblcms2-2
apt-get install -y liblcms2-dev
apt-get install -y libldap-2.5-0
apt-get install -y libldap-common
apt-get install -y libldb2
apt-get install -y libldl2
apt-get install -y liblept5
apt-get install -y liblilv-0-0
apt-get install -y libllvm14
apt-get install -y libllvm15
apt-get install -y liblmdb0
apt-get install -y liblocale-gettext-perl
apt-get install -y liblsan0
apt-get install -y libltdl-dev
apt-get install -y libltdl7
apt-get install -y liblua5.2-0
apt-get install -y liblua5.2-dev
apt-get install -y liblua5.3-0
apt-get install -y liblwp-mediatypes-perl
apt-get install -y liblwp-protocol-https-perl
apt-get install -y liblz4-1
apt-get install -y liblz4-dev
apt-get install -y liblzma-dev
apt-get install -y liblzma5
apt-get install -y liblzo2-2
apt-get install -y libmagic-mgc
apt-get install -y libmagic1
apt-get install -y libmailtools-perl
apt-get install -y libmanette-0.2-0
apt-get install -y libmaxminddb0
apt-get install -y libmbim-glib4
apt-get install -y libmbim-proxy
apt-get install -y libmd-dev
apt-get install -y libmd0
apt-get install -y libmd4c0
apt-get install -y libmediawiki-api-perl
apt-get install -y libmetis5
apt-get install -y libmfx1
apt-get install -y libminizip-dev
apt-get install -y libminizip1
apt-get install -y libmm-glib0
apt-get install -y libmodule-implementation-perl
apt-get install -y libmodule-runtime-perl
apt-get install -y libmongoose2
apt-get install -y libmount-dev
apt-get install -y libmount1
apt-get install -y libmp3lame0
apt-get install -y libmpc3
apt-get install -y libmpdec3
apt-get install -y libmpfr6
apt-get install -y libmpg123-0
apt-get install -y libmro-compat-perl
apt-get install -y libmtdev1
apt-get install -y libmtp-common
apt-get install -y libmtp-runtime
apt-get install -y libmtp9
apt-get install -y libmysofa1
apt-get install -y libmysqlclient-dev
apt-get install -y libmysqlclient21
apt-get install -y libnamespace-autoclean-perl
apt-get install -y libnamespace-clean-perl
apt-get install -y libnautilus-extension1a
apt-get install -y libncurses-dev
apt-get install -y libncurses6
apt-get install -y libncursesw6
apt-get install -y libnet-dbus-perl
apt-get install -y libnet-dns-perl
apt-get install -y libnet-dns-sec-perl
apt-get install -y libnet-domain-tld-perl
apt-get install -y libnet-http-perl
apt-get install -y libnet-ip-perl
apt-get install -y libnet-libidn-perl
apt-get install -y libnet-smtp-ssl-perl
apt-get install -y libnet-ssleay-perl
apt-get install -y libnetcdf-c++4
apt-get install -y libnetcdf-cxx-legacy-dev
apt-get install -y libnetcdf-dev
apt-get install -y libnetcdf19
apt-get install -y libnettle8
apt-get install -y libnfs13
apt-get install -y libnghttp2-14
apt-get install -y libnl-3-200
apt-get install -y libnl-3-dev
apt-get install -y libnl-genl-3-200
apt-get install -y libnl-route-3-200
apt-get install -y libnl-route-3-dev
apt-get install -y libnm0
apt-get install -y libnorm-dev
apt-get install -y libnorm1
apt-get install -y libnotify4
apt-get install -y libnpth0
apt-get install -y libnsl-dev
apt-get install -y libnsl2
apt-get install -y libnspr4
apt-get install -y libnss-mdns
apt-get install -y libnss-systemd
apt-get install -y libnss3
apt-get install -y libntfs-3g89
apt-get install -y libnuma-dev
apt-get install -y libnuma1
apt-get install -y libobjc-11-dev
apt-get install -y libobjc4
apt-get install -y liboctomap-dev
apt-get install -y liboctomap1.9
apt-get install -y libodbc2
apt-get install -y libodbccr2
apt-get install -y libodbcinst2
apt-get install -y libode-dev
apt-get install -y libode8
apt-get install -y libogdi-dev
apt-get install -y libogdi4.1
apt-get install -y libogg-dev
apt-get install -y libogg0
apt-get install -y libogre-1.9-dev
apt-get install -y libogre-1.9.0v5
apt-get install -y libomp-14-dev
apt-get install -y libomp-dev
apt-get install -y libomp5-14
apt-get install -y libopenal-data
apt-get install -y libopenal1
apt-get install -y libopenblas-dev
apt-get install -y libopenblas-pthread-dev
apt-get install -y libopenblas0-pthread
apt-get install -y libopenblas0
apt-get install -y libopencv-calib3d-dev
apt-get install -y libopencv-calib3d4.5d
apt-get install -y libopencv-contrib-dev
apt-get install -y libopencv-contrib4.5d
apt-get install -y libopencv-core-dev
apt-get install -y libopencv-core4.5d
apt-get install -y libopencv-dev
apt-get install -y libopencv-dnn-dev
apt-get install -y libopencv-dnn4.5d
apt-get install -y libopencv-features2d-dev
apt-get install -y libopencv-features2d4.5d
apt-get install -y libopencv-flann-dev
apt-get install -y libopencv-flann4.5d
apt-get install -y libopencv-highgui-dev
apt-get install -y libopencv-highgui4.5d
apt-get install -y libopencv-imgcodecs-dev
apt-get install -y libopencv-imgcodecs4.5d
apt-get install -y libopencv-imgproc-dev
apt-get install -y libopencv-imgproc4.5d
apt-get install -y libopencv-ml-dev
apt-get install -y libopencv-ml4.5d
apt-get install -y libopencv-objdetect-dev
apt-get install -y libopencv-objdetect4.5d
apt-get install -y libopencv-photo-dev
apt-get install -y libopencv-photo4.5d
apt-get install -y libopencv-shape-dev
apt-get install -y libopencv-shape4.5d
apt-get install -y libopencv-stitching-dev
apt-get install -y libopencv-stitching4.5d
apt-get install -y libopencv-superres-dev
apt-get install -y libopencv-superres4.5d
apt-get install -y libopencv-video-dev
apt-get install -y libopencv-video4.5d
apt-get install -y libopencv-videoio-dev
apt-get install -y libopencv-videoio4.5d
apt-get install -y libopencv-videostab-dev
apt-get install -y libopencv-videostab4.5d
apt-get install -y libopencv-viz-dev
apt-get install -y libopencv-viz4.5d
apt-get install -y libopencv4.5-java
apt-get install -y libopencv4.5d-jni
apt-get install -y libopenexr-dev
apt-get install -y libopenexr25
apt-get install -y libopengl-dev
apt-get install -y libopengl0
apt-get install -y libopenjp2-7-dev
apt-get install -y libopenjp2-7
apt-get install -y libopenmpi-dev
apt-get install -y libopenmpi3
apt-get install -y libopenmpt0
apt-get install -y libopenni-dev
apt-get install -y libopenni-sensor-pointclouds0
apt-get install -y libopenni0
apt-get install -y libopenni2-0
apt-get install -y libopenni2-dev
apt-get install -y libopus0
apt-get install -y liborc-0.4-0
apt-get install -y liborocos-kdl-dev
apt-get install -y liborocos-kdl1.5
apt-get install -y libp11-kit0
apt-get install -y libpackage-stash-perl
apt-get install -y libpackage-stash-xs-perl
apt-get install -y libpackagekit-glib2-18
apt-get install -y libpadwalker-perl
apt-get install -y libpam-cap
apt-get install -y libpam-gnome-keyring
apt-get install -y libpam-modules-bin
apt-get install -y libpam-modules
apt-get install -y libpam-runtime
apt-get install -y libpam-systemd
apt-get install -y libpam0g
apt-get install -y libpango-1.0-0
apt-get install -y libpangocairo-1.0-0
apt-get install -y libpangoft2-1.0-0
apt-get install -y libpangoxft-1.0-0
apt-get install -y libpaper-utils
apt-get install -y libpaper1
apt-get install -y libparams-classify-perl
apt-get install -y libparams-util-perl
apt-get install -y libparams-validate-perl
apt-get install -y libparams-validationcompiler-perl
apt-get install -y libparted-fs-resize0
apt-get install -y libparted2
apt-get install -y libpathplan4
apt-get install -y libpcap0.8-dev
apt-get install -y libpcap0.8
apt-get install -y libpciaccess-dev
apt-get install -y libpciaccess0
apt-get install -y libpcl-apps1.12
apt-get install -y libpcl-common1.12
apt-get install -y libpcl-dev
apt-get install -y libpcl-features1.12
apt-get install -y libpcl-filters1.12
apt-get install -y libpcl-io1.12
apt-get install -y libpcl-kdtree1.12
apt-get install -y libpcl-keypoints1.12
apt-get install -y libpcl-ml1.12
apt-get install -y libpcl-octree1.12
apt-get install -y libpcl-outofcore1.12
apt-get install -y libpcl-people1.12
apt-get install -y libpcl-recognition1.12
apt-get install -y libpcl-registration1.12
apt-get install -y libpcl-sample-consensus1.12
apt-get install -y libpcl-search1.12
apt-get install -y libpcl-segmentation1.12
apt-get install -y libpcl-stereo1.12
apt-get install -y libpcl-surface1.12
apt-get install -y libpcl-tracking1.12
apt-get install -y libpcl-visualization1.12
apt-get install -y libpcre16-3
apt-get install -y libpcre2-16-0
apt-get install -y libpcre2-32-0
apt-get install -y libpcre2-8-0
apt-get install -y libpcre2-dev
apt-get install -y libpcre2-posix3
apt-get install -y libpcre3-dev
apt-get install -y libpcre32-3
apt-get install -y libpcre3
apt-get install -y libpcrecpp0v5
apt-get install -y libpcsclite1
apt-get install -y libpeas-1.0-0
apt-get install -y libpeas-common
apt-get install -y libperl4-corelibs-perl
apt-get install -y libperl5.34
apt-get install -y libperlio-gzip-perl
apt-get install -y libpfm4
apt-get install -y libpgm-5.3-0
apt-get install -y libpgm-dev
apt-get install -y libpipeline1
apt-get install -y libpipewire-0.3-0
apt-get install -y libpipewire-0.3-common
apt-get install -y libpipewire-0.3-modules
apt-get install -y libpixman-1-0
apt-get install -y libpixman-1-dev
apt-get install -y libplist3
apt-get install -y libpmix-dev
apt-get install -y libpmix2
apt-get install -y libpng-dev
apt-get install -y libpng-tools
apt-get install -y libpng16-16
apt-get install -y libpocketsphinx3
apt-get install -y libpolkit-agent-1-0
apt-get install -y libpolkit-gobject-1-0
apt-get install -y libpoppler-dev
apt-get install -y libpoppler-glib8
apt-get install -y libpoppler-private-dev
apt-get install -y libpoppler118
apt-get install -y libpopt0
apt-get install -y libpostproc-dev
apt-get install -y libpostproc55
apt-get install -y libpq-dev
apt-get install -y libpq5
apt-get install -y libprocps8
apt-get install -y libproj-dev
apt-get install -y libproj22
apt-get install -y libprotobuf-dev
apt-get install -y libprotobuf-lite23
apt-get install -y libprotobuf23
apt-get install -y libprotoc-dev
apt-get install -y libprotoc23
apt-get install -y libproxy1v5
apt-get install -y libpsl5
apt-get install -y libpsm-infinipath1
apt-get install -y libpsm2-2
apt-get install -y libpthread-stubs0-dev
apt-get install -y libpulse-dev
apt-get install -y libpulse-mainloop-glib0
apt-get install -y libpulse0
apt-get install -y libpyside2-dev
apt-get install -y libpyside2-py3-5.15
apt-get install -y libpython3-dev
apt-get install -y libpython3-stdlib
apt-get install -y libpython3.10-dev
apt-get install -y libpython3.10-minimal
apt-get install -y libpython3.10-stdlib
apt-get install -y libpython3.10
apt-get install -y libqhull-dev
apt-get install -y libqhull-r8.0
apt-get install -y libqhull8.0
apt-get install -y libqhullcpp8.0
apt-get install -y libqmi-glib5
apt-get install -y libqmi-proxy
apt-get install -y libqt5concurrent5
apt-get install -y libqt5core5a
apt-get install -y libqt5dbus5
apt-get install -y libqt5designer5
apt-get install -y libqt5designercomponents5
apt-get install -y libqt5gui5
apt-get install -y libqt5help5
apt-get install -y libqt5network5
apt-get install -y libqt5opengl5-dev
apt-get install -y libqt5opengl5
apt-get install -y libqt5positioning5
apt-get install -y libqt5printsupport5
apt-get install -y libqt5qml5
apt-get install -y libqt5qmlmodels5
apt-get install -y libqt5qmlworkerscript5
apt-get install -y libqt5quick5
apt-get install -y libqt5quickparticles5
apt-get install -y libqt5quickshapes5
apt-get install -y libqt5quicktest5
apt-get install -y libqt5quickwidgets5
apt-get install -y libqt5sensors5
apt-get install -y libqt5sql5-sqlite
apt-get install -y libqt5sql5
apt-get install -y libqt5svg5
apt-get install -y libqt5test5
apt-get install -y libqt5webchannel5
apt-get install -y libqt5webkit5-dev
apt-get install -y libqt5webkit5
apt-get install -y libqt5widgets5
apt-get install -y libqt5xml5
apt-get install -y libqtpropertybrowser5
apt-get install -y libquadmath0
apt-get install -y libqwt-qt5-6
apt-get install -y libqwt-qt5-dev
apt-get install -y librabbitmq4
apt-get install -y libraqm0
apt-get install -y libraw1394-11
apt-get install -y libraw1394-dev
apt-get install -y libraw1394-tools
apt-get install -y libraw20
apt-get install -y librbio2
apt-get install -y librdmacm1
apt-get install -y libreadline-dev
apt-get install -y libreadline8
apt-get install -y libreadonly-perl
apt-get install -y libref-util-perl
apt-get install -y libref-util-xs-perl
apt-get install -y librhash0
apt-get install -y librole-tiny-perl
apt-get install -y librsvg2-2
apt-get install -y librsvg2-common
apt-get install -y librtmp1
apt-get install -y librttopo-dev
apt-get install -y librttopo1
apt-get install -y librubberband2
apt-get install -y libsamplerate0
apt-get install -y libsasl2-2
apt-get install -y libsasl2-modules-db
apt-get install -y libsasl2-modules
apt-get install -y libsdformat9-9
apt-get install -y libsdformat9-dev
apt-get install -y libsdl2-2.0-0
apt-get install -y libsdl2-dev
apt-get install -y libseccomp2
apt-get install -y libsecret-1-0
apt-get install -y libsecret-common
apt-get install -y libselinux1-dev
apt-get install -y libselinux1
apt-get install -y libsemanage-common
apt-get install -y libsemanage2
apt-get install -y libsensors-config
apt-get install -y libsensors5
apt-get install -y libsepol-dev
apt-get install -y libsepol2
apt-get install -y libserd-0-0
apt-get install -y libserf-1-1
apt-get install -y libshiboken2-dev
apt-get install -y libshiboken2-py3-5.15
apt-get install -y libshine3
apt-get install -y libshout3
apt-get install -y libsigsegv2
apt-get install -y libsimbody-dev
apt-get install -y libsimbody3.6
apt-get install -y libslang2
apt-get install -y libsliplu1
apt-get install -y libsm-dev
apt-get install -y libsm6
apt-get install -y libsmartcols1
apt-get install -y libsmbclient
apt-get install -y libsnappy1v5
apt-get install -y libsndfile1
apt-get install -y libsndio-dev
apt-get install -y libsndio7.0
apt-get install -y libsocket++1
apt-get install -y libsodium-dev
apt-get install -y libsodium23
apt-get install -y libsord-0-0
apt-get install -y libsoup2.4-1
apt-get install -y libsoup2.4-common
apt-get install -y libsource-highlight-common
apt-get install -y libsource-highlight4v5
apt-get install -y libsoxr0
apt-get install -y libspa-0.2-modules
apt-get install -y libspatialite-dev
apt-get install -y libspatialite7
apt-get install -y libspdlog-dev
apt-get install -y libspdlog1
apt-get install -y libspecio-perl
apt-get install -y libspectre1
apt-get install -y libspeex1
apt-get install -y libsphinxbase3
apt-get install -y libspnav0
apt-get install -y libspqr2
apt-get install -y libsqlite3-0
apt-get install -y libsqlite3-dev
apt-get install -y libsratom-0-0
apt-get install -y libsrt1.4-gnutls
apt-get install -y libss2
apt-get install -y libssh-4
apt-get install -y libssh-gcrypt-4
apt-get install -y libssl-dev
apt-get install -y libssl3
apt-get install -y libstdc++-11-dev
apt-get install -y libstdc++6
apt-get install -y libstemmer0d
apt-get install -y libsub-exporter-perl
apt-get install -y libsub-exporter-progressive-perl
apt-get install -y libsub-identify-perl
apt-get install -y libsub-install-perl
apt-get install -y libsub-name-perl
apt-get install -y libsub-quote-perl
apt-get install -y libsuitesparse-dev
apt-get install -y libsuitesparseconfig5
apt-get install -y libsuperlu-dev
apt-get install -y libsuperlu5
apt-get install -y libsvn-perl
apt-get install -y libsvn1
apt-get install -y libswresample-dev
apt-get install -y libswresample3
apt-get install -y libswscale-dev
apt-get install -y libswscale5
apt-get install -y libsynctex2
apt-get install -y libsystemd0
apt-get install -y libsz2
apt-get install -y libtag1v5-vanilla
apt-get install -y libtag1v5
apt-get install -y libtalloc2
apt-get install -y libtar-dev
apt-get install -y libtar0
apt-get install -y libtasn1-6
apt-get install -y libtbb-dev
apt-get install -y libtbb12
apt-get install -y libtbb2
apt-get install -y libtbbmalloc2
apt-get install -y libtcl8.6
apt-get install -y libtdb1
apt-get install -y libterm-readkey-perl
apt-get install -y libtesseract4
apt-get install -y libtevent0
apt-get install -y libtext-iconv-perl
apt-get install -y libthai-data
apt-get install -y libthai0
apt-get install -y libtheora-dev
apt-get install -y libtheora0
apt-get install -y libtie-ixhash-perl
apt-get install -y libtiff-dev
apt-get install -y libtiff5
apt-get install -y libtiffxx5
apt-get install -y libtimedate-perl
apt-get install -y libtinfo6
apt-get install -y libtinyobjloader-dev
apt-get install -y libtinyobjloader1
apt-get install -y libtinyxml-dev
apt-get install -y libtinyxml2-9
apt-get install -y libtinyxml2-dev
apt-get install -y libtinyxml2.6.2v5
apt-get install -y libtirpc-common
apt-get install -y libtirpc-dev
apt-get install -y libtirpc3
apt-get install -y libtk8.6
apt-get install -y libtool-bin
apt-get install -y libtool
apt-get install -y libtorrent-rasterbar2.0
apt-get install -y libtotem-plparser-common
apt-get install -y libtotem-plparser18
apt-get install -y libtracker-sparql-3.0-0
apt-get install -y libtry-tiny-perl
apt-get install -y libtsan0
apt-get install -y libtwolame0
apt-get install -y libtypes-serialiser-perl
apt-get install -y libubsan1
apt-get install -y libuchardet0
apt-get install -y libucx0
apt-get install -y libudev-dev
apt-get install -y libudev1
apt-get install -y libudfread0
apt-get install -y libudisks2-0
apt-get install -y libumfpack5
apt-get install -y libunistring2
apt-get install -y libunity-protocol-private0
apt-get install -y libunity-scopes-json-def-desktop
apt-get install -y libunity9
apt-get install -y libunwind-dev
apt-get install -y libunwind8
apt-get install -y libupower-glib3
apt-get install -y liburdfdom-model3.0
apt-get install -y liburdfdom-world3.0
apt-get install -y liburi-perl
apt-get install -y liburing2
apt-get install -y liburiparser-dev
apt-get install -y liburiparser1
apt-get install -y libusb-1.0-0-dev
apt-get install -y libusb-1.0-0
apt-get install -y libusb-1.0-doc
apt-get install -y libusbmuxd6
apt-get install -y libutempter0
apt-get install -y libutf8proc2
apt-get install -y libutfcpp-dev
apt-get install -y libuuid1
apt-get install -y libuv1
apt-get install -y libv4l-0
apt-get install -y libv4lconvert0
apt-get install -y libva-drm2
apt-get install -y libva-x11-2
apt-get install -y libva2
apt-get install -y libvariable-magic-perl
apt-get install -y libvdpau1
apt-get install -y libvidstab1.1
apt-get install -y libvisual-0.4-0
apt-get install -y libvolume-key1
apt-get install -y libvorbis0a
apt-get install -y libvorbisenc2
apt-get install -y libvorbisfile3
apt-get install -y libvpx7
apt-get install -y libvtk9-dev
apt-get install -y libvtk9-java
apt-get install -y libvtk9-qt-dev
apt-get install -y libvtk9.1-qt
apt-get install -y libvtk9.1
apt-get install -y libvulkan-dev
apt-get install -y libvulkan1
apt-get install -y libwacom-bin
apt-get install -y libwacom-common
apt-get install -y libwacom9
apt-get install -y libwavpack1
apt-get install -y libwayland-bin
apt-get install -y libwayland-client0
apt-get install -y libwayland-cursor0
apt-get install -y libwayland-dev
apt-get install -y libwayland-egl1
apt-get install -y libwayland-server0
apt-get install -y libwbclient0
apt-get install -y libwebkit2gtk-4.0-37
apt-get install -y libwebp-dev
apt-get install -y libwebp7
apt-get install -y libwebpdemux2
apt-get install -y libwebpmux3
apt-get install -y libwebrtc-audio-processing1
apt-get install -y libwmf-0.2-7
apt-get install -y libwmf-dev
apt-get install -y libwmflite-0.2-7
apt-get install -y libwoff1
apt-get install -y libwpe-1.0-1
apt-get install -y libwpebackend-fdo-1.0-1
apt-get install -y libwww-perl
apt-get install -y libwww-robotrules-perl
apt-get install -y libx11-6
apt-get install -y libx11-data
apt-get install -y libx11-dev
apt-get install -y libx11-protocol-perl
apt-get install -y libx11-xcb1
apt-get install -y libx264-163
apt-get install -y libx265-199
apt-get install -y libx265-dev
apt-get install -y libxau-dev
apt-get install -y libxau6
apt-get install -y libxaw7-dev
apt-get install -y libxaw7
apt-get install -y libxcb-dri2-0
apt-get install -y libxcb-dri3-0
apt-get install -y libxcb-glx0
apt-get install -y libxcb-icccm4
apt-get install -y libxcb-image0
apt-get install -y libxcb-keysyms1
apt-get install -y libxcb-present0
apt-get install -y libxcb-randr0
apt-get install -y libxcb-render-util0
apt-get install -y libxcb-render0-dev
apt-get install -y libxcb-render0
apt-get install -y libxcb-shape0
apt-get install -y libxcb-shm0-dev
apt-get install -y libxcb-shm0
apt-get install -y libxcb-sync1
apt-get install -y libxcb-util1
apt-get install -y libxcb-xfixes0
apt-get install -y libxcb-xinerama0
apt-get install -y libxcb-xinput0
apt-get install -y libxcb-xkb1
apt-get install -y libxcb1-dev
apt-get install -y libxcb1
apt-get install -y libxcomposite1
apt-get install -y libxcursor-dev
apt-get install -y libxcursor1
apt-get install -y libxdamage1
apt-get install -y libxdmcp-dev
apt-get install -y libxdmcp6
apt-get install -y libxerces-c-dev
apt-get install -y libxerces-c3.2
apt-get install -y libxext-dev
apt-get install -y libxext6
apt-get install -y libxfixes-dev
apt-get install -y libxfixes3
apt-get install -y libxft-dev
apt-get install -y libxft2
apt-get install -y libxi-dev
apt-get install -y libxi6
apt-get install -y libxinerama-dev
apt-get install -y libxinerama1
apt-get install -y libxkbcommon-dev
apt-get install -y libxkbcommon-x11-0
apt-get install -y libxkbcommon0
apt-get install -y libxkbfile1
apt-get install -y libxkbregistry0
apt-get install -y libxml-parser-perl
apt-get install -y libxml-twig-perl
apt-get install -y libxml-xpathengine-perl
apt-get install -y libxml2-dev
apt-get install -y libxml2-utils
apt-get install -y libxml2
apt-get install -y libxmlb2
apt-get install -y libxmu-dev
apt-get install -y libxmu-headers
apt-get install -y libxmu6
apt-get install -y libxmuu1
apt-get install -y libxnvctrl0
apt-get install -y libxpm-dev
apt-get install -y libxpm4
apt-get install -y libxrandr-dev
apt-get install -y libxrandr2
apt-get install -y libxrender-dev
apt-get install -y libxrender1
apt-get install -y libxshmfence1
apt-get install -y libxsimd-dev
apt-get install -y libxslt1.1
apt-get install -y libxss-dev
apt-get install -y libxss1
apt-get install -y libxstring-perl
apt-get install -y libxt-dev
apt-get install -y libxt6
apt-get install -y libxtensor-dev
apt-get install -y libxtst6
apt-get install -y libxv-dev
apt-get install -y libxv1
apt-get install -y libxvidcore4
apt-get install -y libxxf86dga1
apt-get install -y libxxf86vm-dev
apt-get install -y libxxf86vm1
apt-get install -y libxxhash0
apt-get install -y libyaml-0-2
apt-get install -y libyaml-cpp-dev
apt-get install -y libyaml-cpp0.7
apt-get install -y libyaml-dev
apt-get install -y libyaml-libyaml-perl
apt-get install -y libyaml-perl
apt-get install -y libyelp0
apt-get install -y libz3-4
apt-get install -y libz3-dev
apt-get install -y libzimg2
apt-get install -y libzip-dev
apt-get install -y libzip4
apt-get install -y libzmq3-dev
apt-get install -y libzmq5
apt-get install -y libzstd-dev
apt-get install -y libzstd1
apt-get install -y libzvbi-common
apt-get install -y libzvbi0
apt-get install -y libzzip-0-13
apt-get install -y linux-libc-dev
apt-get install -y llvm-14-dev
apt-get install -y llvm-14-linker-tools
apt-get install -y llvm-14-runtime
apt-get install -y llvm-14-tools
apt-get install -y llvm-14
apt-get install -y locales
apt-get install -y login
apt-get install -y logsave
apt-get install -y lsb-base
apt-get install -y lsb-release
apt-get install -y lsof
apt-get install -y lto-disabled-list
apt-get install -y m4
apt-get install -y mailcap
apt-get install -y make
apt-get install -y man-db
apt-get install -y manpages-dev
apt-get install -y manpages
apt-get install -y mawk
apt-get install -y media-types
apt-get install -y mercurial-common
apt-get install -y mercurial
apt-get install -y mesa-va-drivers
apt-get install -y mesa-vdpau-drivers
apt-get install -y mesa-vulkan-drivers
apt-get install -y mime-support
apt-get install -y mlocate
apt-get install -y modemmanager
apt-get install -y mount
apt-get install -y mpi-default-bin
apt-get install -y mpi-default-dev
apt-get install -y mysql-common
apt-get install -y nano
apt-get install -y nautilus-data
apt-get install -y nautilus
apt-get install -y ncurses-base
apt-get install -y ncurses-bin
apt-get install -y netbase
apt-get install -y networkd-dispatcher
apt-get install -y nlohmann-json3-dev
apt-get install -y notification-daemon
apt-get install -y ntfs-3g
apt-get install -y ocl-icd-libopencl1
apt-get install -y opencv-data
apt-get install -y openjdk-11-jdk-headless
apt-get install -y openjdk-11-jdk
apt-get install -y openjdk-11-jre-headless
apt-get install -y openjdk-11-jre
apt-get install -y openmpi-bin
apt-get install -y openmpi-common
apt-get install -y openni-utils
apt-get install -y openssh-client
apt-get install -y openssl
apt-get install -y p11-kit-modules
apt-get install -y p11-kit
apt-get install -y packagekit-tools
apt-get install -y packagekit
apt-get install -y parted
apt-get install -y passwd
apt-get install -y patch
apt-get install -y perl-base
apt-get install -y perl-modules-5.34
apt-get install -y perl-openssl-defaults
apt-get install -y perl
apt-get install -y pinentry-curses
apt-get install -y pinentry-gnome3
apt-get install -y pipewire-bin
apt-get install -y pipewire-media-session
apt-get install -y pipewire
apt-get install -y pkexec
apt-get install -y pkg-config
apt-get install -y plocate
apt-get install -y pocketsphinx-en-us
apt-get install -y policykit-1
apt-get install -y polkitd
apt-get install -y poppler-data
apt-get install -y procps
apt-get install -y proj-bin
apt-get install -y proj-data
apt-get install -y protobuf-compiler
apt-get install -y psmisc
apt-get install -y publicsuffix
apt-get install -y pybind11-dev
apt-get install -y pydocstyle
apt-get install -y pyflakes3
apt-get install -y pyqt5-dev
apt-get install -y python-apt-common
apt-get install -y python-babel-localedata
apt-get install -y python-matplotlib-data
apt-get install -y python3-appdirs
apt-get install -y python3-apt
apt-get install -y python3-argcomplete
apt-get install -y python3-attr
apt-get install -y python3-babel
apt-get install -y python3-beniget
apt-get install -y python3-blinker
apt-get install -y python3-bloom
apt-get install -y python3-breezy
apt-get install -y python3-brotli
apt-get install -y python3-bs4
apt-get install -y python3-cairo
apt-get install -y python3-catkin-pkg-modules
apt-get install -y python3-catkin-pkg
apt-get install -y python3-certifi
apt-get install -y python3-cffi-backend
apt-get install -y python3-chardet
apt-get install -y python3-colcon-argcomplete
apt-get install -y python3-colcon-bash
apt-get install -y python3-colcon-cd
apt-get install -y python3-colcon-cmake
apt-get install -y python3-colcon-common-extensions
apt-get install -y python3-colcon-core
apt-get install -y python3-colcon-defaults
apt-get install -y python3-colcon-devtools
apt-get install -y python3-colcon-installed-package-information
apt-get install -y python3-colcon-library-path
apt-get install -y python3-colcon-metadata
apt-get install -y python3-colcon-notification
apt-get install -y python3-colcon-output
apt-get install -y python3-colcon-override-check
apt-get install -y python3-colcon-package-information
apt-get install -y python3-colcon-package-selection
apt-get install -y python3-colcon-parallel-executor
apt-get install -y python3-colcon-pkg-config
apt-get install -y python3-colcon-powershell
apt-get install -y python3-colcon-python-setup-py
apt-get install -y python3-colcon-recursive-crawl
apt-get install -y python3-colcon-ros
apt-get install -y python3-colcon-test-result
apt-get install -y python3-colcon-zsh
apt-get install -y python3-configobj
apt-get install -y python3-cov-core
apt-get install -y python3-coverage
apt-get install -y python3-cryptography
apt-get install -y python3-cycler
apt-get install -y python3-dateutil
apt-get install -y python3-dbus
apt-get install -y python3-decorator
apt-get install -y python3-deprecated
apt-get install -y python3-dev
apt-get install -y python3-distlib
apt-get install -y python3-distro-info
apt-get install -y python3-distro
apt-get install -y python3-distutils
apt-get install -y python3-docutils
apt-get install -y python3-dulwich
apt-get install -y python3-empy
apt-get install -y python3-fastbencode
apt-get install -y python3-fastimport
apt-get install -y python3-filelock
apt-get install -y python3-flake8
apt-get install -y python3-fonttools
apt-get install -y python3-fs
apt-get install -y python3-gast
apt-get install -y python3-gi-cairo
apt-get install -y python3-gi
apt-get install -y python3-github
apt-get install -y python3-gitlab
apt-get install -y python3-gpg
apt-get install -y python3-html5lib
apt-get install -y python3-httplib2
apt-get install -y python3-idna
apt-get install -y python3-importlib-metadata
apt-get install -y python3-iniconfig
apt-get install -y python3-jeepney
apt-get install -y python3-jinja2
apt-get install -y python3-jwt
apt-get install -y python3-keyring
apt-get install -y python3-kiwisolver
apt-get install -y python3-lark
apt-get install -y python3-launchpadlib
apt-get install -y python3-lazr.restfulclient
apt-get install -y python3-lazr.uri
apt-get install -y python3-ldb
apt-get install -y python3-lib2to3
apt-get install -y python3-lxml
apt-get install -y python3-lz4
apt-get install -y python3-markupsafe
apt-get install -y python3-matplotlib
apt-get install -y python3-mccabe
apt-get install -y python3-minimal
apt-get install -y python3-more-itertools
apt-get install -y python3-mpi4py
apt-get install -y python3-mpmath
apt-get install -y python3-nacl
apt-get install -y python3-netifaces
apt-get install -y python3-nose2
apt-get install -y python3-nose
apt-get install -y python3-notify2
apt-get install -y python3-numpy
apt-get install -y python3-oauthlib
apt-get install -y python3-olefile
apt-get install -y python3-opencv
apt-get install -y python3-packaging
apt-get install -y python3-patiencediff
apt-get install -y python3-pcl
apt-get install -y python3-pil.imagetk
apt-get install -y python3-pil
apt-get install -y python3-pip
apt-get install -y python3-pkg-resources
apt-get install -y python3-pluggy
apt-get install -y python3-ply
apt-get install -y python3-psutil
apt-get install -y python3-py
apt-get install -y python3-pycodestyle
apt-get install -y python3-pydocstyle
apt-get install -y python3-pydot
apt-get install -y python3-pyflakes
apt-get install -y python3-pygments
apt-get install -y python3-pygraphviz
apt-get install -y python3-pyparsing
apt-get install -y python3-pyqt5.qtsvg
apt-get install -y python3-pyqt5.sip
apt-get install -y python3-pyqt5
apt-get install -y python3-pyside2.qtcore
apt-get install -y python3-pyside2.qtgui
apt-get install -y python3-pyside2.qtsvg
apt-get install -y python3-pyside2.qtwidgets
apt-get install -y python3-pytest-cov
apt-get install -y python3-pytest
apt-get install -y python3-pythran
apt-get install -y python3-requests-toolbelt
apt-get install -y python3-requests
apt-get install -y python3-roman
apt-get install -y python3-rosdep-modules
apt-get install -y python3-rosdep
apt-get install -y python3-rosdistro-modules
apt-get install -y python3-rosdistro
apt-get install -y python3-rospkg-modules
apt-get install -y python3-rospkg
apt-get install -y python3-scipy
apt-get install -y python3-secretstorage
apt-get install -y python3-setuptools
apt-get install -y python3-sip-dev
apt-get install -y python3-sip
apt-get install -y python3-six
apt-get install -y python3-snowballstemmer
apt-get install -y python3-software-properties
apt-get install -y python3-soupsieve
apt-get install -y python3-sympy
apt-get install -y python3-talloc
apt-get install -y python3-tk
apt-get install -y python3-toml
apt-get install -y python3-typeguard
apt-get install -y python3-tz
apt-get install -y python3-ufolib2
apt-get install -y python3-unicodedata2
apt-get install -y python3-urllib3
apt-get install -y python3-vcstool
apt-get install -y python3-vcstools
apt-get install -y python3-vtk9
apt-get install -y python3-wadllib
apt-get install -y python3-webencodings
apt-get install -y python3-wheel
apt-get install -y python3-wrapt
apt-get install -y python3-yaml
apt-get install -y python3-zipp
apt-get install -y python3-zmq
apt-get install -y python3.10-dev
apt-get install -y python3.10-minimal
apt-get install -y python3.10
apt-get install -y python3
apt-get install -y qbittorrent
apt-get install -y qdoc-qt5
apt-get install -y qhelpgenerator-qt5
apt-get install -y qt5-assistant
apt-get install -y qt5-gtk-platformtheme
apt-get install -y qt5-qmake-bin
apt-get install -y qt5-qmake
apt-get install -y qt5-qmltooling-plugins
apt-get install -y qtattributionsscanner-qt5
apt-get install -y qtbase5-dev-tools
apt-get install -y qtbase5-dev
apt-get install -y qtchooser
apt-get install -y qtdeclarative5-dev-tools
apt-get install -y qtdeclarative5-dev
apt-get install -y qttools5-dev-tools
apt-get install -y qttools5-dev
apt-get install -y qttools5-private-dev
apt-get install -y qttranslations5-l10n
apt-get install -y ranger
apt-get install -y readline-common
apt-get install -y ros-build-essential
apt-get install -y ros-dev-tools
apt-get install -y ros-humble-ackermann-msgs
apt-get install -y ros-humble-action-msgs
apt-get install -y ros-humble-actionlib-msgs
apt-get install -y ros-humble-ament-cmake-auto
apt-get install -y ros-humble-ament-cmake-copyright
apt-get install -y ros-humble-ament-cmake-core
apt-get install -y ros-humble-ament-cmake-cppcheck
apt-get install -y ros-humble-ament-cmake-cpplint
apt-get install -y ros-humble-ament-cmake-export-definitions
apt-get install -y ros-humble-ament-cmake-export-dependencies
apt-get install -y ros-humble-ament-cmake-export-include-directories
apt-get install -y ros-humble-ament-cmake-export-interfaces
apt-get install -y ros-humble-ament-cmake-export-libraries
apt-get install -y ros-humble-ament-cmake-export-link-flags
apt-get install -y ros-humble-ament-cmake-export-targets
apt-get install -y ros-humble-ament-cmake-flake8
apt-get install -y ros-humble-ament-cmake-gen-version-h
apt-get install -y ros-humble-ament-cmake-gmock
apt-get install -y ros-humble-ament-cmake-gtest
apt-get install -y ros-humble-ament-cmake-include-directories
apt-get install -y ros-humble-ament-cmake-libraries
apt-get install -y ros-humble-ament-cmake-lint-cmake
apt-get install -y ros-humble-ament-cmake-pep257
apt-get install -y ros-humble-ament-cmake-pytest
apt-get install -y ros-humble-ament-cmake-python
apt-get install -y ros-humble-ament-cmake-ros
apt-get install -y ros-humble-ament-cmake-target-dependencies
apt-get install -y ros-humble-ament-cmake-test
apt-get install -y ros-humble-ament-cmake-uncrustify
apt-get install -y ros-humble-ament-cmake-version
apt-get install -y ros-humble-ament-cmake-xmllint
apt-get install -y ros-humble-ament-cmake
apt-get install -y ros-humble-ament-copyright
apt-get install -y ros-humble-ament-cppcheck
apt-get install -y ros-humble-ament-cpplint
apt-get install -y ros-humble-ament-flake8
apt-get install -y ros-humble-ament-index-cpp
apt-get install -y ros-humble-ament-index-python
apt-get install -y ros-humble-ament-lint-auto
apt-get install -y ros-humble-ament-lint-cmake
apt-get install -y ros-humble-ament-lint-common
apt-get install -y ros-humble-ament-lint
apt-get install -y ros-humble-ament-package
apt-get install -y ros-humble-ament-pep257
apt-get install -y ros-humble-ament-uncrustify
apt-get install -y ros-humble-ament-xmllint
apt-get install -y ros-humble-angles
apt-get install -y ros-humble-apriltag-msgs
apt-get install -y ros-humble-apriltag-ros
apt-get install -y ros-humble-apriltag
apt-get install -y ros-humble-backward-ros
apt-get install -y ros-humble-behaviortree-cpp-v3
apt-get install -y ros-humble-bond
apt-get install -y ros-humble-bondcpp
apt-get install -y ros-humble-builtin-interfaces
apt-get install -y ros-humble-camera-calibration-parsers
apt-get install -y ros-humble-camera-info-manager
apt-get install -y ros-humble-cartographer-ros-msgs
apt-get install -y ros-humble-cartographer-ros
apt-get install -y ros-humble-cartographer
apt-get install -y ros-humble-class-loader
apt-get install -y ros-humble-common-interfaces
apt-get install -y ros-humble-composition-interfaces
apt-get install -y ros-humble-compressed-depth-image-transport
apt-get install -y ros-humble-compressed-image-transport
apt-get install -y ros-humble-console-bridge-vendor
apt-get install -y ros-humble-control-msgs
apt-get install -y ros-humble-control-toolbox
apt-get install -y ros-humble-controller-interface
apt-get install -y ros-humble-controller-manager-msgs
apt-get install -y ros-humble-controller-manager
apt-get install -y ros-humble-cv-bridge
apt-get install -y ros-humble-diagnostic-msgs
apt-get install -y ros-humble-diagnostic-updater
apt-get install -y ros-humble-domain-coordinator
apt-get install -y ros-humble-eigen3-cmake-module
apt-get install -y ros-humble-example-interfaces
apt-get install -y ros-humble-fastcdr
apt-get install -y ros-humble-fastrtps-cmake-module
apt-get install -y ros-humble-fastrtps
apt-get install -y ros-humble-filters
apt-get install -y ros-humble-foonathan-memory-vendor
apt-get install -y ros-humble-gazebo-dev
apt-get install -y ros-humble-gazebo-msgs
apt-get install -y ros-humble-gazebo-plugins
apt-get install -y ros-humble-gazebo-ros-pkgs
apt-get install -y ros-humble-gazebo-ros2-control
apt-get install -y ros-humble-gazebo-ros
apt-get install -y ros-humble-generate-parameter-library-py
apt-get install -y ros-humble-generate-parameter-library
apt-get install -y ros-humble-geographic-msgs
apt-get install -y ros-humble-geometry-msgs
apt-get install -y ros-humble-geometry2
apt-get install -y ros-humble-gmock-vendor
apt-get install -y ros-humble-grid-map-cmake-helpers
apt-get install -y ros-humble-grid-map-core
apt-get install -y ros-humble-grid-map-cv
apt-get install -y ros-humble-grid-map-filters
apt-get install -y ros-humble-grid-map-loader
apt-get install -y ros-humble-grid-map-msgs
apt-get install -y ros-humble-grid-map-pcl
apt-get install -y ros-humble-grid-map-ros
apt-get install -y ros-humble-grid-map-rviz-plugin
apt-get install -y ros-humble-grid-map-sdf
apt-get install -y ros-humble-grid-map-visualization
apt-get install -y ros-humble-gtest-vendor
apt-get install -y ros-humble-hardware-interface
apt-get install -y ros-humble-hls-lfcd-lds-driver
apt-get install -y ros-humble-ignition-cmake2-vendor
apt-get install -y ros-humble-ignition-math6-vendor
apt-get install -y ros-humble-image-geometry
apt-get install -y ros-humble-image-transport-plugins
apt-get install -y ros-humble-image-transport
apt-get install -y ros-humble-imu-filter-madgwick
apt-get install -y ros-humble-interactive-markers
apt-get install -y ros-humble-joint-state-publisher-gui
apt-get install -y ros-humble-joint-state-publisher
apt-get install -y ros-humble-joy
apt-get install -y ros-humble-kdl-parser
apt-get install -y ros-humble-keyboard-handler
apt-get install -y ros-humble-kinematics-interface-kdl
apt-get install -y ros-humble-kinematics-interface
apt-get install -y ros-humble-laser-geometry
apt-get install -y ros-humble-launch-ros
apt-get install -y ros-humble-launch-testing-ament-cmake
apt-get install -y ros-humble-launch-testing-ros
apt-get install -y ros-humble-launch-testing
apt-get install -y ros-humble-launch-xml
apt-get install -y ros-humble-launch-yaml
apt-get install -y ros-humble-launch
apt-get install -y ros-humble-libcurl-vendor
apt-get install -y ros-humble-libg2o
apt-get install -y ros-humble-libnabo
apt-get install -y ros-humble-libpointmatcher
apt-get install -y ros-humble-librealsense2
apt-get install -y ros-humble-libstatistics-collector
apt-get install -y ros-humble-libyaml-vendor
apt-get install -y ros-humble-lifecycle-msgs
apt-get install -y ros-humble-map-msgs
apt-get install -y ros-humble-message-filters
apt-get install -y ros-humble-nav-msgs
apt-get install -y ros-humble-nav2-common
apt-get install -y ros-humble-nav2-map-server
apt-get install -y ros-humble-nav2-msgs
apt-get install -y ros-humble-nav2-util
apt-get install -y ros-humble-octomap-mapping
apt-get install -y ros-humble-octomap-msgs
apt-get install -y ros-humble-octomap-ros
apt-get install -y ros-humble-octomap-rviz-plugins
apt-get install -y ros-humble-octomap-server
apt-get install -y ros-humble-octomap
apt-get install -y ros-humble-ompl
apt-get install -y ros-humble-orocos-kdl-vendor
apt-get install -y ros-humble-osrf-pycommon
apt-get install -y ros-humble-parameter-traits
apt-get install -y ros-humble-pcl-conversions
apt-get install -y ros-humble-pcl-msgs
apt-get install -y ros-humble-pcl-ros
apt-get install -y ros-humble-pluginlib
apt-get install -y ros-humble-pybind11-vendor
apt-get install -y ros-humble-python-cmake-module
apt-get install -y ros-humble-python-qt-binding
apt-get install -y ros-humble-qt-dotgraph
apt-get install -y ros-humble-qt-gui-cpp
apt-get install -y ros-humble-qt-gui-py-common
apt-get install -y ros-humble-qt-gui
apt-get install -y ros-humble-rcl-action
apt-get install -y ros-humble-rcl-interfaces
apt-get install -y ros-humble-rcl-lifecycle
apt-get install -y ros-humble-rcl-logging-interface
apt-get install -y ros-humble-rcl-logging-spdlog
apt-get install -y ros-humble-rcl-yaml-param-parser
apt-get install -y ros-humble-rcl
apt-get install -y ros-humble-rclcpp-action
apt-get install -y ros-humble-rclcpp-components
apt-get install -y ros-humble-rclcpp-lifecycle
apt-get install -y ros-humble-rclcpp
apt-get install -y ros-humble-rclpy
apt-get install -y ros-humble-rcpputils
apt-get install -y ros-humble-rcutils
apt-get install -y ros-humble-realsense2-camera-msgs
apt-get install -y ros-humble-realtime-tools
apt-get install -y ros-humble-resource-retriever
apt-get install -y ros-humble-rmw-dds-common
apt-get install -y ros-humble-rmw-fastrtps-cpp
apt-get install -y ros-humble-rmw-fastrtps-shared-cpp
apt-get install -y ros-humble-rmw-implementation-cmake
apt-get install -y ros-humble-rmw-implementation
apt-get install -y ros-humble-rmw
apt-get install -y ros-humble-robot-state-publisher
apt-get install -y ros-humble-ros-base
apt-get install -y ros-humble-ros-core
apt-get install -y ros-humble-ros-environment
apt-get install -y ros-humble-ros-workspace
apt-get install -y ros-humble-ros2-control-test-assets
apt-get install -y ros-humble-ros2action
apt-get install -y ros-humble-ros2bag
apt-get install -y ros-humble-ros2cli-common-extensions
apt-get install -y ros-humble-ros2cli
apt-get install -y ros-humble-ros2component
apt-get install -y ros-humble-ros2doctor
apt-get install -y ros-humble-ros2interface
apt-get install -y ros-humble-ros2launch
apt-get install -y ros-humble-ros2lifecycle
apt-get install -y ros-humble-ros2multicast
apt-get install -y ros-humble-ros2node
apt-get install -y ros-humble-ros2param
apt-get install -y ros-humble-ros2pkg
apt-get install -y ros-humble-ros2run
apt-get install -y ros-humble-ros2service
apt-get install -y ros-humble-ros2topic
apt-get install -y ros-humble-rosbag2-compression-zstd
apt-get install -y ros-humble-rosbag2-compression
apt-get install -y ros-humble-rosbag2-cpp
apt-get install -y ros-humble-rosbag2-interfaces
apt-get install -y ros-humble-rosbag2-py
apt-get install -y ros-humble-rosbag2-storage-default-plugins
apt-get install -y ros-humble-rosbag2-storage
apt-get install -y ros-humble-rosbag2-transport
apt-get install -y ros-humble-rosbag2
apt-get install -y ros-humble-rosgraph-msgs
apt-get install -y ros-humble-rosidl-adapter
apt-get install -y ros-humble-rosidl-cli
apt-get install -y ros-humble-rosidl-cmake
apt-get install -y ros-humble-rosidl-default-generators
apt-get install -y ros-humble-rosidl-default-runtime
apt-get install -y ros-humble-rosidl-generator-c
apt-get install -y ros-humble-rosidl-generator-cpp
apt-get install -y ros-humble-rosidl-generator-py
apt-get install -y ros-humble-rosidl-parser
apt-get install -y ros-humble-rosidl-runtime-c
apt-get install -y ros-humble-rosidl-runtime-cpp
apt-get install -y ros-humble-rosidl-runtime-py
apt-get install -y ros-humble-rosidl-typesupport-c
apt-get install -y ros-humble-rosidl-typesupport-cpp
apt-get install -y ros-humble-rosidl-typesupport-fastrtps-c
apt-get install -y ros-humble-rosidl-typesupport-fastrtps-cpp
apt-get install -y ros-humble-rosidl-typesupport-interface
apt-get install -y ros-humble-rosidl-typesupport-introspection-c
apt-get install -y ros-humble-rosidl-typesupport-introspection-cpp
apt-get install -y ros-humble-rpyutils
apt-get install -y ros-humble-rqt-action
apt-get install -y ros-humble-rqt-bag-plugins
apt-get install -y ros-humble-rqt-bag
apt-get install -y ros-humble-rqt-common-plugins
apt-get install -y ros-humble-rqt-console
apt-get install -y ros-humble-rqt-graph
apt-get install -y ros-humble-rqt-gui-cpp
apt-get install -y ros-humble-rqt-gui-py
apt-get install -y ros-humble-rqt-gui
apt-get install -y ros-humble-rqt-image-view
apt-get install -y ros-humble-rqt-msg
apt-get install -y ros-humble-rqt-plot
apt-get install -y ros-humble-rqt-publisher
apt-get install -y ros-humble-rqt-py-common
apt-get install -y ros-humble-rqt-py-console
apt-get install -y ros-humble-rqt-reconfigure
apt-get install -y ros-humble-rqt-service-caller
apt-get install -y ros-humble-rqt-shell
apt-get install -y ros-humble-rqt-srv
apt-get install -y ros-humble-rqt-topic
apt-get install -y ros-humble-rqt
apt-get install -y ros-humble-rsl
apt-get install -y ros-humble-rviz-assimp-vendor
apt-get install -y ros-humble-rviz-common
apt-get install -y ros-humble-rviz-default-plugins
apt-get install -y ros-humble-rviz-imu-plugin
apt-get install -y ros-humble-rviz-ogre-vendor
apt-get install -y ros-humble-rviz-rendering
apt-get install -y ros-humble-rviz2
apt-get install -y ros-humble-sdl2-vendor
apt-get install -y ros-humble-sensor-msgs-py
apt-get install -y ros-humble-sensor-msgs
apt-get install -y ros-humble-shape-msgs
apt-get install -y ros-humble-shared-queues-vendor
apt-get install -y ros-humble-slam-toolbox
apt-get install -y ros-humble-smclib
apt-get install -y ros-humble-spdlog-vendor
apt-get install -y ros-humble-sqlite3-vendor
apt-get install -y ros-humble-sros2-cmake
apt-get install -y ros-humble-sros2
apt-get install -y ros-humble-statistics-msgs
apt-get install -y ros-humble-std-msgs
apt-get install -y ros-humble-std-srvs
apt-get install -y ros-humble-stereo-msgs
apt-get install -y ros-humble-tango-icons-vendor
apt-get install -y ros-humble-tcb-span
apt-get install -y ros-humble-teleop-twist-joy
apt-get install -y ros-humble-teleop-twist-keyboard
apt-get install -y ros-humble-test-msgs
apt-get install -y ros-humble-tf2-bullet
apt-get install -y ros-humble-tf2-eigen-kdl
apt-get install -y ros-humble-tf2-eigen
apt-get install -y ros-humble-tf2-geometry-msgs
apt-get install -y ros-humble-tf2-kdl
apt-get install -y ros-humble-tf2-msgs
apt-get install -y ros-humble-tf2-py
apt-get install -y ros-humble-tf2-ros-py
apt-get install -y ros-humble-tf2-ros
apt-get install -y ros-humble-tf2-sensor-msgs
apt-get install -y ros-humble-tf2-tools
apt-get install -y ros-humble-tf2
apt-get install -y ros-humble-theora-image-transport
apt-get install -y ros-humble-tinyxml-vendor
apt-get install -y ros-humble-tinyxml2-vendor
apt-get install -y ros-humble-tl-expected
apt-get install -y ros-humble-tracetools
apt-get install -y ros-humble-trajectory-msgs
apt-get install -y ros-humble-turtlesim
apt-get install -y ros-humble-twist-mux
apt-get install -y ros-humble-uncrustify-vendor
apt-get install -y ros-humble-unique-identifier-msgs
apt-get install -y ros-humble-urdf-parser-plugin
apt-get install -y ros-humble-urdf
apt-get install -y ros-humble-urdfdom-headers
apt-get install -y ros-humble-urdfdom
apt-get install -y ros-humble-velodyne-driver
apt-get install -y ros-humble-velodyne-laserscan
apt-get install -y ros-humble-velodyne-msgs
apt-get install -y ros-humble-velodyne-pointcloud
apt-get install -y ros-humble-velodyne
apt-get install -y ros-humble-vision-msgs
apt-get install -y ros-humble-visualization-msgs
apt-get install -y ros-humble-xacro
apt-get install -y ros-humble-yaml-cpp-vendor
apt-get install -y ros-humble-zstd-vendor
apt-get install -y rpcsvc-proto
apt-get install -y rtkit
apt-get install -y samba-libs
apt-get install -y sdformat9-sdf
apt-get install -y sed
apt-get install -y sensible-utils
apt-get install -y session-migration
apt-get install -y sgml-base
apt-get install -y sgml-data
apt-get install -y shared-mime-info
apt-get install -y shiboken2
apt-get install -y sip-dev
apt-get install -y snapd
apt-get install -y software-properties-common
apt-get install -y sound-theme-freedesktop
apt-get install -y squashfs-tools
apt-get install -y ssl-cert
apt-get install -y subversion
apt-get install -y sudo
apt-get install -y systemd-hwe-hwdb
apt-get install -y systemd-sysv
apt-get install -y systemd-timesyncd
apt-get install -y systemd
apt-get install -y sysvinit-utils
apt-get install -y tango-icon-theme
apt-get install -y tar
apt-get install -y tcl-dev
apt-get install -y tcl8.6-dev
apt-get install -y tcl8.6
apt-get install -y tcl
apt-get install -y tf
apt-get install -y tk-dev
apt-get install -y tk8.6-blt2.5
apt-get install -y tk8.6-dev
apt-get install -y tk8.6
apt-get install -y tk
apt-get install -y tmux
apt-get install -y tracker-extract
apt-get install -y tracker-miner-fs
apt-get install -y tracker
apt-get install -y tzdata
apt-get install -y ubuntu-keyring
apt-get install -y ubuntu-mono
apt-get install -y ucf
apt-get install -y udev
apt-get install -y udisks2
apt-get install -y unattended-upgrades
apt-get install -y uncrustify
apt-get install -y unicode-data
apt-get install -y unixodbc-common
apt-get install -y unixodbc-dev
apt-get install -y upower
apt-get install -y usb-modeswitch-data
apt-get install -y usb-modeswitch
apt-get install -y usbmuxd
apt-get install -y usrmerge
apt-get install -y util-linux
apt-get install -y uuid-dev
apt-get install -y va-driver-all
apt-get install -y vdpau-driver-all
apt-get install -y vim-common
apt-get install -y vim-runtime
apt-get install -y vim
apt-get install -y vtk9
apt-get install -y w3m-img
apt-get install -y w3m
apt-get install -y wavemon
apt-get install -y wget
apt-get install -y wpasupplicant
apt-get install -y x11-common
apt-get install -y x11-apps
apt-get install -y x11-utils
apt-get install -y x11-xserver-utils
apt-get install -y x11proto-dev
apt-get install -y xauth
apt-get install -y xbitmaps
apt-get install -y xdg-dbus-proxy
apt-get install -y xdg-desktop-portal-gtk
apt-get install -y xdg-desktop-portal
apt-get install -y xdg-user-dirs
apt-get install -y xdg-utils
apt-get install -y xkb-data
apt-get install -y xml-core
apt-get install -y xorg-sgml-doctools
apt-get install -y xterm
apt-get install -y xtl-dev
apt-get install -y xtrans-dev
apt-get install -y xxd
apt-get install -y xz-utils
apt-get install -y yelp-xsl
apt-get install -y yelp
apt-get install -y yudit-common
apt-get install -y zenity-common
apt-get install -y zenity
apt-get install -y zlib1g-dev
apt-get install -y zlib1g
apt-get install -y zsh-common
apt-get install -y zsh

pip install setuptools==58.2.0